# Generated by Django 5.0.1 on 2024-01-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
