# Generated by Django 5.0.1 on 2024-01-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
