# Generated by Django 5.0.1 on 2024-01-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
