# Generated by Django 5.0.1 on 2024-01-16 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rated',
            field=models.ManyToManyField(related_name='rated_products', through='product.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
