# Generated by Django 5.0.1 on 2024-01-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_rating_product_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rated',
        ),
    ]
